### ISSUE TITLE
add ajpanel

### ISSUE THREAD

**Issue by biko-73** [fairbird/TSipanel-pyhon3#1]
[enigma2-plugin-extensions-ajpanel_v9.3.0_all_deb.zip](https://github.com/fairbird/TSipanel-pyhon3/files/14466782/enigma2-plugin-extensions-ajpanel_v9.3.0_all_deb.zip)
[enigma2-plugin-extensions-ajpanel_v9.3.0_all_ipk.zip](https://github.com/fairbird/TSipanel-pyhon3/files/14466783/enigma2-plugin-extensions-ajpanel_v9.3.0_all_ipk.zip)

it always updated on https://github.com/biko-73/AjPanel
if can do script which update when version are updated will be great
or i will upload new version every time will update manually 

********************************
that some plugin i  keep it updated

- BouquetMakerXtream
https://github.com/biko-73/BouquetMakerXtream

- xstreamity
https://github.com/biko-73/xstreamity

- Visual_Weather
https://github.com/biko-73/Visual_Weather

- History_Zap_Selector
https://github.com/biko-73/History_Zap_Selector

- Sherlockmod
https://github.com/biko-73/Sherlockmod

- jediepgxtream
https://github.com/biko-73/jediepgxtream

- EvgQuickSignal
https://github.com/biko-73/EvgQuickSignal

- ip2sat
https://github.com/biko-73/ip2sat

- TheWeather
https://github.com/biko-73/TheWeather

- AccuWeather
https://github.com/biko-73/AccuWeather

**Comment by zozman21** [comment]
great work

**Comment by fairbird** [comment]
No need to open issue ...
Just Push commit to git with ipk file (Not script) Should be ipk file for example (ajpanel) make commit to ipk file and push it in to (https://github.com/fairbird/TSipanel-pyhon3/tree/main/Plugins) Do not push zip file .. Just ipk. Then when I have free time I will test it first after that I will be merge it if all fine.

Any plugins  present on the image feed no need to upload it again to pane such as (xstreamity, BouquetMakerXtream)

**Comment by fairbird** [comment]
I have upload some plugins as @biko-73 advice and download already ipk file from his git .. And add new folder (Plugins-Weather) ...
https://github.com/fairbird/TSipanel-pyhon3/commit/bc900677adf5190241bea753e9fdb3256712ebfe
